cnn_4_110_model:
  hidden_units : 64
  hidden_layers : 2
  blocks: 4
  channels: 110

cnn_6_380_model:
  hidden_units : 64
  hidden_layers : 2
  blocks: 6
  channels: 380
  
train:
  epochs : 20
  learning_rate : 3e-4
  batch_size : 10
  optimizer: "adamW"
  dropout_rate: 10
  weight_decay: 1e-4
  w0: 20

test:
  epochs : 20
  batch_size : 10

data:
  data_dir : "/Users/applem2/Downloads/NN/NN-project/data/datasets"

dump:
  weights_path: "/Users/applem2/Downloads/NN/NN-project/results/checkpoints/weights"
  model_path: "/Users/applem2/Downloads/NN/NN-project/results/checkpoints/model"

devices:
  cuda: "cuda"
  mps:  "mps"
  tpu:  "tpu"
  cpu:  "cpu"

