comment hydra if you want the configuration to be saved
hydra:
  run:
    dir: .
  output_subdir: null
  job_logging: disabled


net:
  data_dim: 2
  in_channels: 3
  out_channels: 10
  hidden_channels: 140
  no_blocks: 4
  bias: False

kernel:
  kernel_no_layers: 4
  kernel_hidden_channels: 32
  kernel_size: 33
  conv_type: "conv"
  fft_threshold: 50

# TODO
train:
  warm_up_epochs: 10
  epochs : 20
  learning_rate : 3e-4
  batch_size : 10
  loss_fn: "crossEntropy"
  optimizer: "adamW"
  dropout_rate: 10
  weight_decay: 1e-4
  w0: 20

test:
  epochs : 20
  batch_size : 10

data:
  data_dir : "/Users/applem2/Downloads/NN/NN-project/data/datasets"

dump:
  weights_path: "/Users/applem2/Downloads/NN/NN-project/results/checkpoints/weights"
  model_path: "/Users/applem2/Downloads/NN/NN-project/results/checkpoints/model"

devices:
  cuda: "cuda"
  mps:  "mps"
  tpu:  "tpu"
  cpu:  "cpu"

