net:
  data_dim: 
  in_channels: 
  out_channels: 
  hidden_channels: 140
  no_blocks: 4
  bias: True
  causal: False

kernel:
  kernel_no_layers: 3
  kernel_hidden_channels: 32
  kernel_size: 33
  conv_type: "conv"
  fft_threshold: 50
  omega_0: 

load_model:
  pre_trained: True
  model: "top"

train:
  logger: True
  callbacks: True
  profiler: True
  accelerator: "cpu"
  devices: "auto"
  warmup_epochs: 10
  epochs: 
  learning_rate: 
  batch_size: 
  start_factor: 1e-8
  end_factor: 1.0
  dropout_rate: 
  weight_decay: 
  max_epoch_no_improvement: 200

data:
  data_dir : "datasets"
  dataset : "s_pathfinder"
  # this line is used only in datamodules that uses LRA as dataset (pathfinder, listops, etc.)
  light_lra: False

# Comment the two sections below to make hydra generate the files again
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .